# Generated by Django 2.2 on 2019-04-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('sale_start', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('sale_end', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_on_sale', models.BooleanField(max_length=100)),
                ('current_price', models.FloatField()),
            ],
        ),
    ]
